version: "3.3"

x-app: &app-tpl
  env_file:
    - .env
  build:
    context: .
    dockerfile: Dockerfile


services:
  db:
    image: postgres:12
#    volumes:
#      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  migrations:
    <<: *app-tpl
    depends_on:
      - db
    entrypoint: ["/bin/sh","-c"]
    command:
      - python app/backend_pre_start.py && alembic upgrade head

  initial_data:
    <<: *app-tpl
    depends_on:
      - migrations
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - alembic upgrade head && python app/initial_data.py

  app:
    <<: *app-tpl
    depends_on:
      - migrations
    ports:
      - "8000:8000"

#volumes:
#  app-db-data:

