version: '3'

dotenv: ['.env']

env:
  PYTHONPATH: {sh: "pwd"}

vars:
  MODULE: github.com/itimky/word-of-wisom

tasks:
  gen-migrations:
    cmds:
      - alembic revision --autogenerate

  migrate:
    - alembic upgrade head

  initial-data:
    cmds:
      - python initial_data.py

  format:
    cmds:
      # Sort imports one per line, so autoflake can remove unused imports
      - isort --recursive --force-single-line-imports --apply app
      - autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place app --exclude=__init__.py
      - black app
      - isort --recursive --apply app

  lint:
    cmds:
      - mypy .
      - black app --check
      - isort --check-only app --skip ./alembic/
      - flake8